name = "laburen-asistente-ventas-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "MCP", class_name = "LaburenMCP" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LaburenMCP"]

[[d1_databases]]
binding = "laburen_db"
database_name = "laburen-db"
database_id = "a5e9302b-7d02-48de-a817-2ce86b422663"
