name = "laburen-asistente-ventas-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "MCP_SERVER", class_name = "LaburenMCP" }
]

[[migrations]]
tag = "v1"
new_classes = ["LaburenMCP"]

[[d1_databases]]
binding = "DB"
database_name = "laburen-db"
database_id = "to-be-replaced-with-real-id"
